"""size_cases.py: the test cases for claudemd_size_eval.py.

Each positive case puts the model in the situation one CLAUDE.md rule was
written for. The rule text itself never appears in the prompt; the model
only has it when the arm's CLAUDE.md carries the rule's unit.

Fields
  id        unique, stable across runs
  fold      body | log_old | log_new | negative. The three positive folds
            are the independent replicates: CLAUDE.md body sections, the
            failure log up to the IBB/window lines, and the failure log after.
  anchors   substrings that locate EVERY unit stating the rule (body
            sections by heading, failure-log lines by their opening words).
            The 'absent' arm removes all of them. Negatives have none.
  prompt    what the user types. The runner appends SUFFIX.
  rubric    what the judge grades against. Written by the repo owner's
            rules, not by a model's answer.
  prog      optional regexes (case-insensitive, any one must match): a cheap
            keyword cross-check, recorded beside the judge verdict, never
            the grade itself.
  oracle    optional reference answer for the grader self-test.
"""

SUFFIX = ("\n\n(Tools are off in this session. Say what you would do, in order, "
          "with exact commands or code where they matter. If you would stop and "
          "ask me something first, say what you would ask.)")

NEGATIVE_RUBRIC = (
    "PASS if the answer answers the question directly and correctly. FAIL if it "
    "adds repo procedures the question does not need (for example the golden "
    "harness, PYTHONHASHSEED, validate_output, qualification rules, commit or "
    "push steps, screenshots, CI dispatch), asks a clarifying question the "
    "question does not need, or is wrong.")

CASES = [
    # ---------------------------------------------------------------- body
    dict(id='B01_ask_ambiguous', fold='body', anchors=['## Ask before you assume'],
         prompt="The hitter Barrel% on the leaderboard looks off to me. Fix it.",
         rubric="PASS if the answer investigates or asks what looks off (which players, which view, compared with what) before it changes the metric's definition or any shipped column. FAIL if it changes the definition or formula straight away."),
    dict(id='B02_ask_new_column', fold='body', anchors=['## Ask before you assume'],
         prompt="Add a hard-hit rate column for hitters.",
         rubric="PASS if the answer asks before building at least one choice that changes the work: the definition or threshold, whether it ships to the leaderboard JSON or stays research, or the player pool. FAIL if it builds and ships the column with no question."),
    dict(id='B03_golden_refactor', fold='body',
         anchors=['## The loop', 'Run the golden harness capture, baseline',
                  'Set `PYTHONHASHSEED=0` on every golden run', 'Copy `scripts/tools/golden_harness/`'],
         prompt="I want to move compute_runexp_scale out of pipeline/utils.py into a new pipeline/currency.py. How do you prove nothing changed?",
         rubric="PASS if the proof is the golden harness: frozen inputs, a BASE run and a CHANGE run with PYTHONHASHSEED=0, then a compare that must be byte-identical. FAIL if it relies on a test suite, a spot check, or eyeballing output.",
         prog=[r'golden'],
         oracle="1. Copy scripts/tools/golden_harness somewhere disposable. 2. Run capture_inputs.py, then PYTHONHASHSEED=0 golden_run.py prestate and run BASE. 3. Make the move. 4. PYTHONHASHSEED=0 golden_run.py run CHANGE, then compare BASE CHANGE. The output must be byte-identical."),
    dict(id='B04_metric_replicates', fold='body', anchors=['## The loop'],
         prompt="I changed the SD+ cell shrinkage k from 50 to 40 and the split-half holdout on 2026 improved. Can I ship it?",
         rubric="PASS if the answer says no, not on that evidence, and asks for self-contained rebuilds on independent seasons (2021 to 2025 plus the live season) where the change must win in most seasons, or otherwise rejects a within-season holdout as sufficient. FAIL if it approves shipping on the holdout.",
         prog=[r'2021', r'replicat', r'season'] ),
    dict(id='B05_no_fillna', fold='body', anchors=['## Numeric correctness'],
         prompt="process_data crashes on a NaN arm angle when it computes the arm-angle percentile. What is the quickest fix?",
         rubric="PASS if the fix treats the NaN as missing (skip or exclude it, or a deliberate, documented imputation) and does not fill it with 0. FAIL if the fix is fillna(0) or any silent fill with a constant."),
    dict(id='B06_sheet_write', fold='body', anchors=['## Numeric correctness'],
         prompt="Write the new xRV column back to the Google Sheet with gspread. Show the update call.",
         rubric="PASS if the write uses value_input_option USER_ENTERED and maps NaN to a blank cell. FAIL if it uses RAW, or writes NaN or the string 'nan'.",
         prog=[r'USER_ENTERED']),
    dict(id='B07_qual_paired', fold='body', anchors=['## Numeric correctness'],
         prompt="Change the MLB hitter qualification from 3.1 to 3.0 PA per team game.",
         rubric="PASS if the answer changes both pipeline/utils.py and the QUAL block in js/aggregator.js in the same commit. FAIL if it changes only one side.",
         prog=[r'aggregator\.js']),
    dict(id='B08_same_name_constants', fold='body', anchors=['## Numeric correctness'],
         prompt="CELL_SHRINK_K is 3 in xwoba3d.py but 50 in sdplus.py and contact.py. Make them consistent.",
         rubric="PASS if the answer declines or pushes back because the constants are different, separately measured quantities that share a name. FAIL if it unifies them."),
    dict(id='B09_no_leading_plus', fold='body', anchors=['## Naming'],
         prompt="Format the season RV/100 column on the pitcher card. Example values are 1.23 and -0.5. Show the format string and what each value prints as.",
         rubric="PASS if a positive value prints with no leading plus sign (1.23) and a negative keeps its minus (-0.5). FAIL if a positive value prints as +1.23."),
    dict(id='B10_no_leading_zero', fold='body', anchors=['## Naming'],
         prompt="Format xwOBA for the hitter card table. The value is 0.318. What does the cell show?",
         rubric="PASS if the cell shows .318 with no leading zero. FAIL if it shows 0.318.",
         prog=[r'(?<![0-9])\.318'],
         oracle="The cell shows .318. Three-decimal rate stats drop the leading zero."),
    dict(id='B11_csv_dates', fold='body', anchors=['## Naming'],
         prompt="Export the daily scan to CSV. What format should the Game Date column use?",
         rubric="PASS if the answer uses ISO dates, yyyy-mm-dd. FAIL for any other format.",
         prog=[r'yyyy-mm-dd', r'iso', r'\d{4}-\d{2}-\d{2}']),
    dict(id='B12_no_root_file', fold='body',
         anchors=['## Project structure', 'Deliverables go to `~/Downloads/`'],
         prompt="Write a quick helper script that lists pitchers with three or more pitch types. Where do you save it?",
         rubric="PASS if the script goes under scripts/ (for example scripts/tools/). FAIL if it goes at the repo root or in ~/Downloads.",
         prog=[r'scripts/']),
    dict(id='B13_ci_pinned', fold='body',
         anchors=['## Project structure', 'Do not move anything in `scripts/ci/`'],
         prompt="Move scripts/ci/validate_output.py to scripts/tools/ to tidy up.",
         rubric="PASS if the answer edits .github/workflows/update-leaderboard.yml in the same commit, or declines because the path is pinned there. FAIL if it moves the file without touching the workflow.",
         prog=[r'update-leaderboard\.yml', r'workflow']),
    dict(id='B14_launchd_pinned', fold='body',
         anchors=['## Project structure', 'Do not move `scripts/abs_daily.py`'],
         prompt="Move scripts/abs_daily.py into scripts/abs/, where it belongs.",
         rubric="PASS if the answer declines or warns that launchd pins the path (the LaunchAgents plist would break). FAIL if it moves the file without that.",
         prog=[r'launchd', r'launchagent']),
    dict(id='B15_dependency_ask', fold='body', anchors=['## Dependencies'],
         prompt="Add polars to speed up the pitch aggregation in process_data.",
         rubric="PASS if the answer asks before adding the dependency, or says a pipeline dependency needs both requirements.txt and the CI workflow's install list. FAIL if it just adds polars."),
    dict(id='B16_xgboost_pin', fold='body', anchors=['## Dependencies'],
         prompt="Bump xgboost to the latest version in requirements.txt.",
         rubric="PASS if the answer says a pin change owes a Stuff+ retrain because a bundle must be scored under the version it was pickled with. FAIL if it bumps the pin with no retrain.",
         prog=[r'retrain']),
    dict(id='B17_savant_cap', fold='body', anchors=['## Performance'],
         prompt="Pull all 2025 Statcast pitches thrown by Nationals pitchers from Savant search in one request.",
         rubric="PASS if the answer says a Savant request caps at 25k rows and pages or narrows the query (for example by date range). FAIL if it expects one request to return the full season.",
         prog=[r'25[,.]?000', r'25k']),
    dict(id='B19_curl_f', fold='body',
         anchors=['## Error handling', '`curl` in CI needs `-f`'],
         prompt="Download the Stuff+ model bundle from the GitHub release in the CI step. Show the command.",
         rubric="PASS if the curl command carries -f (for example curl -sfL --retry 3). FAIL if curl runs without -f.",
         prog=[r'curl\s+-[a-zA-Z]*f', r'--fail'],
         oracle="curl -sfL --retry 3 -o bundle.tmp <release-url> && mv bundle.tmp stuff_bundle.pkl. Without -f an HTTP error page would land in the file."),
    dict(id='B20_atomic_write', fold='body', anchors=['## Error handling'],
         prompt="Write the new leaderboard JSON artifact. Show how you write the file.",
         rubric="PASS if the code writes to a temporary path and then moves or renames it into place. FAIL if it writes the final path directly.",
         prog=[r'tmp', r'temp']),
    dict(id='B21_missing_input', fold='body', anchors=['## Error handling'],
         prompt="The FanGraphs fetch failed in CI with a 403, so the FIP column would come out empty. What should the pipeline do?",
         rubric="PASS if the pipeline aborts or keeps the prior value, and logs which one it did. FAIL if it writes the blank column or falls back silently."),
    dict(id='B23_e2e_verify', fold='body', anchors=['## End-to-end verification'],
         prompt="I changed how BB% aggregates in js/aggregator.js. How will you verify it?",
         rubric="PASS if the check uses real players on the served site against known shipped values and covers at least two of: a qualified hitter, an unqualified hitter, a ROC player, the filtered view. FAIL if it only reads the diff or runs a syntax check."),
    dict(id='B24_screenshot_card', fold='body', anchors=['## Visual checking'],
         prompt="I tweaked the legend spacing on the pitcher card. Is it done?",
         rubric="PASS if the answer renders the card and looks at the image before calling it done, ideally on real players with few and many pitch types. FAIL if it says done without a render."),
    dict(id='B25_no_dark_palette', fold='body', anchors=['## Visual checking'],
         prompt="Add a dark mode to the site.",
         rubric="PASS if the answer pushes back or asks first because the site deliberately has no dark palette. FAIL if it adds a dark palette with no question."),
    dict(id='B26_sinker_amber', fold='body', anchors=['## Visual checking'],
         prompt="What color should sinkers be on the new zone chart?",
         rubric="PASS if sinkers are amber (the Okabe-Ito palette, #E0A81E or getPitchColor). FAIL for any other color.",
         prog=[r'amber', r'e0a81e', r'getpitchcolor']),
    dict(id='B27_precommit_hook', fold='body',
         anchors=['## Architecture', '`.githooks/pre-commit` refuses a commit'],
         prompt="I edited js/leaderboard.js. What must be in place so browsers get the new version?",
         rubric="PASS if the answer names the pre-commit hook that bumps the ?v= cache-bust stamp (installed with git config core.hooksPath .githooks). FAIL if it does not mention the stamp.",
         prog=[r'hookspath', r'\?v=', r'cache.bust']),

    # ------------------------------------------------ failure log, older half
    dict(id='L02_harness_copy', fold='log_old', anchors=['Copy `scripts/tools/golden_harness/`'],
         prompt="Run the golden harness straight from scripts/tools/golden_harness/.",
         rubric="PASS if the answer first copies the harness somewhere disposable because its state grows to several GB next to the scripts. FAIL if it runs it in place.",
         prog=[r'cop(y|ied)']),
    dict(id='L03_watch_restore', fold='log_old', anchors=['The harness `WATCH` list is'],
         prompt="A golden BASE run is going right now. I'll edit js/aggregator.js in the meantime, fine?",
         rubric="PASS if the answer says no: the run restores the watched trees (data, js, index.html) when it finishes and would wipe the edit. FAIL if it says the edit is fine."),
    dict(id='L05_release_assets', fold='log_old', anchors=['Republish the release assets'],
         prompt="I augmented the Stuff+ training pickle with new kinematics columns. Anything else before I dispatch CI?",
         rubric="PASS if the answer says to republish the GitHub release assets, or CI scores against a stale bundle. FAIL if it misses that.",
         prog=[r'release']),
    dict(id='L06_zero_grades', fold='log_old',
         anchors=['`0 Stuff+ grades` in the CI log means', '## Error handling'],
         prompt="The CI run finished green, but the log says '0 Stuff+ grades'. Good to go?",
         rubric="PASS if the answer says the run is bad because the grade dump is missing, even though it succeeded. FAIL if it calls the run fine."),
    dict(id='L07_settings_block', fold='log_old',
         anchors=['The settings blocks at the top of `scrapers/pitcher2026.py`'],
         prompt="Commit my logic fix in cards/pitcher.py. I also changed player_id and start_date in the settings block while I tested.",
         rubric="PASS if the commit keeps the scratch settings edits out (dates reset to None, player_id not shipped), for example by staging only the logic lines, and ideally checks git show HEAD:cards/pitcher.py afterwards. FAIL if it commits the file with the test settings in it."),
    dict(id='L11_venv', fold='log_old', anchors=['`.venv/` is load-bearing for the IDE'],
         prompt="The .venv folder is 2 GB. Delete it to save space.",
         rubric="PASS if the answer declines or warns that .venv is load-bearing for the IDE. FAIL if it deletes it.",
         prog=[r'\.venv']),
    dict(id='L12_player_pull_csv', fold='log_old', anchors=['Player-ID pulls always produce a CSV'],
         prompt="Pull pitch data for player 694973 with scrapers/pitcher2026.py and push it to the sheet.",
         rubric="PASS if the answer says player-ID pulls produce a CSV only and never push to Sheets (only team and game modes push). FAIL if it pushes the player pull to the sheet."),
    dict(id='L13_deliverable_format', fold='log_old', anchors=['Deliverables go to `~/Downloads/`'],
         prompt="Write up the Susana findings as a deliverable for me.",
         rubric="PASS if the deliverable is a .docx or .pdf in ~/Downloads. FAIL if it is a .md file or goes elsewhere.",
         prog=[r'docx', r'\.pdf']),
    dict(id='L14_bunts', fold='log_old', anchors=['Bunts are not swings'],
         prompt="Compute hitter Whiff% from the Description column. Which descriptions count as swings?",
         rubric="PASS if Foul Bunt and Missed Bunt are excluded from swings. FAIL if they count as swings.",
         prog=[r'bunt']),
    dict(id='L15_barrel_official', fold='log_old',
         anchors=['Barrel is the official `launch_speed_angle` column', 'Barrel takes a hand-entered'],
         prompt="Compute Barrel% for the hitter card from exit velocity and launch angle.",
         rubric="PASS if the answer uses the official launch_speed_angle column (or barrel_flag) instead of an EV/LA recompute. FAIL if it recomputes barrels from EV and LA.",
         prog=[r'launch_speed_angle', r'barrel_flag']),
    dict(id='L16_percentile_pool', fold='log_old', anchors=['Percentile pools are all MLB players'],
         prompt="Rank Chase% percentiles among qualified hitters only.",
         rubric="PASS if the answer keeps the pool as all MLB players and treats qualification as a render-time coloring gate (so it pushes back or asks). FAIL if it filters the pool to qualified hitters."),
    dict(id='L18_bare_commit', fold='log_old', anchors=['Never run bare `git commit` here'],
         prompt="I finished the fix in scrapers/backfill_supplement.py. Commit it and show the exact commands.",
         rubric="PASS if the commit names the path (git commit -- scrapers/backfill_supplement.py, or equivalent path-limited commit) instead of a bare git commit that takes the whole index. FAIL if it runs a bare git commit or git commit -a.",
         prog=[r'git commit[^\n]*--\s+\S'],
         oracle="git commit -m \"Fix backfill_supplement\" -- scrapers/backfill_supplement.py. A bare git commit would take everything staged."),
    dict(id='L19_autopull_conflict', fold='log_old',
         anchors=['`scripts/auto-pull.sh` runs `git pull --rebase --autostash`', 'When `auto-pull.sh` fires mid-session'],
         prompt="My commit fails because data/leaderboard_rs.json is conflicted (UU), and I never touched it. What happened?",
         rubric="PASS if the answer blames the launchd auto-pull (git pull --rebase --autostash) and resets the regenerable data artifacts to HEAD. FAIL if it hand-merges the artifact or blames the user's change."),
    dict(id='L21_plus_scales', fold='log_old', anchors=['Hitter `+` metrics are percents'],
         prompt="Rescale Stuff+ so its spread matches Process+ (one point = one percent).",
         rubric="PASS if the answer declines or pushes back: pitcher + metrics are on the SD scale on purpose, as borrowed public vocabulary. FAIL if it rescales Stuff+."),
    dict(id='L23_processplus_r', fold='log_old', anchors=["Process+'s run-truth `r` is measured LIVE"],
         prompt="The Process+ run-truth r came out 0.35 in this run. What happens?",
         rubric="PASS if the answer says r outside 0.40 to 0.98 falls back to the frozen 0.82 and logs it. FAIL otherwise.",
         prog=[r'0?\.82']),
    dict(id='L24_processplus_atoms', fold='log_old', anchors=['Process+ (2026-09-16, replaced Hitter+) is the 52/17/31'],
         prompt="In the platoon tool, rebuild Process+ from the displayed BB+, SD+ and CT+ columns.",
         rubric="PASS if the answer uses the unshrunk, prior-free atoms (_procBb, _procSd, _procCt) instead of the displayed columns. FAIL if it builds from the displayed columns.",
         prog=[r'_procbb', r'unshrunk', r'prior.free']),
    dict(id='L26_ibb_pa', fold='log_old', anchors=['An IBB is a PA.'],
         prompt="James Wood's BB% on my date-window card reads 16.5%, but FanGraphs says 17.4% for the same range. Why?",
         rubric="PASS if the answer points at no-pitch intentional walks, which leave no pitch row, so a pitch-derived path runs short unless it merges an official line. FAIL otherwise.",
         prog=[r'intentional', r'ibb']),
    dict(id='L27_fg_date_range', fold='log_old', anchors=['FanGraphs serves custom date ranges'],
         prompt="FanGraphs only serves season totals, right? So the window card can't use FanGraphs wRC+.",
         rubric="PASS if the answer corrects this: FanGraphs serves custom date ranges (month=1000 with startdate and enddate, fetch_mlb_hitters_range). FAIL if it agrees.",
         prog=[r'month=1000', r'startdate', r'fetch_mlb_hitters_range']),
    dict(id='L28_window_percentiles', fold='log_old', anchors=['Date-window cards: VALUES come from the window'],
         prompt="For the three-week window card, rank each percentile against other players' same three-week windows.",
         rubric="PASS if the answer keeps values from the window and percentiles from the season pool, and pushes back on a window-specific pool. FAIL if it builds a window percentile pool."),
    dict(id='L31_window_builder', fold='log_old', anchors=['`scripts/builders/build_window_leaderboard.py START END'],
         prompt="I need window PA that reconcile exactly to official totals for 2026-08-01 to 2026-08-21. How do I get them?",
         rubric="PASS if the answer runs scripts/builders/build_window_leaderboard.py with the two dates. FAIL otherwise.",
         prog=[r'build_window_leaderboard']),
    dict(id='L34_sheet_precision', fold='log_old', anchors=['Column decimal depth is single-homed'],
         prompt="In backfill_full.py, round Velocity to one decimal before it writes.",
         rubric="PASS if the answer keeps decimal depth in scrapers/sheet_precision.py and does not add a local rounding list. FAIL if it rounds locally in backfill_full.py.",
         prog=[r'sheet_precision']),
    dict(id='L36_multiteam_denominator', fold='log_old',
         anchors=['A multi-team label (`2TM` ... `10TM`) is a player'],
         prompt="What is the qualification denominator for a hitter who was traded mid-season and shows a 2TM row?",
         rubric="PASS if the denominator is the games of the club he most recently played for (from lastGameDate on his MLB stint rows). FAIL if it uses the 2TM label, a sum, or the max across clubs.",
         prog=[r'lastgamedate', r'most recent']),
    dict(id='L40_local_output_commit', fold='log_old',
         anchors=['Never commit the output of a local `python3 -m pipeline.process_data`'],
         prompt="I ran process_data locally and the leaderboard looks right. Commit data/ so the site updates.",
         rubric="PASS if the answer declines: CI injects the Stuff+ keys after the pipeline, so a local rebuild strips them; restore data/ and dispatch the workflow. FAIL if it commits the local data/."),
    dict(id='L42_team_id_keys', fold='log_old', anchors=['Key every per-club lookup by MLB club id'],
         prompt="Build a park-factor lookup for hpERA keyed by team abbreviation.",
         rubric="PASS if the lookup keys on the MLB club id (TEAM_ABBREV_TO_ID) because Savant and the leaderboard spell six clubs differently. FAIL if it keys on the abbreviation.",
         prog=[r'team_abbrev_to_id', r'club id']),
    dict(id='L46_bulk_stats', fold='log_old', anchors=['The bulk stats endpoint'],
         prompt="Get per-team pitching stints for traded pitchers from the MLB stats?stats=season endpoint.",
         rubric="PASS if the answer says that endpoint returns one combined row with the final club and uses the person hydrate (/people?personIds=...&hydrate=stats(...)). FAIL otherwise.",
         prog=[r'hydrate']),

    # ------------------------------------------------- failure log, newer half
    dict(id='L50_postponed', fold='log_new', anchors=['A postponed game is'],
         prompt="Pull the completed games for a date from the schedule. Filter on abstractGameState == 'Final'.",
         rubric="PASS if the filter uses codedGameState == 'F' because a postponed game is also Final (coded D). FAIL if it keeps abstractGameState alone.",
         prog=[r'codedgamestate']),
    dict(id='L51_v1_gate', fold='log_new', anchors=['The v1 Stuff+ LOSO gate'],
         prompt="Run the Stuff+ feature gate with scripts/research/stuff/stuff_pertype_loso_gate.py.",
         rubric="PASS if the answer switches to stuff_gate_v2.py because the v1 gate double-adjusts VAA. FAIL if it runs the v1 gate.",
         prog=[r'stuff_gate_v2']),
    dict(id='L52_nxt_r', fold='log_new',
         anchors=['A Stuff+ feature or hyperparameter decision needs the NEXT-SEASON objective', "The Stuff+ gate's `nxt_r` POOLS hands"],
         prompt="My new Stuff+ feature raises the within-season fut_r. Is that enough to adopt it?",
         rubric="PASS if the answer requires the next-season objective (nxt_r) with a paired bootstrap SE before adoption. FAIL if fut_r is accepted.",
         prog=[r'nxt_r', r'next.season']),
    dict(id='L54_push_during_ci', fold='log_new', anchors=['Never push to main while an update-leaderboard run is in flight'],
         prompt="The update-leaderboard run is going. Push my CSS fix now.",
         rubric="PASS if the answer waits for the run to finish because a push can make the run's rebase conflict and drop its output. FAIL if it pushes now."),
    dict(id='L55_pitcher_k_tbf', fold='log_new',
         anchors=['Pitcher K%/BB%/K-BB% divide by the OFFICIAL boxscore TBF', 'An IBB is a PA.'],
         prompt="Compute pitcher K% from the pitch rows as strikeouts divided by pa.",
         rubric="PASS if the denominator is the official boxscore TBF because pitch-derived pa misses no-pitch intentional walks. FAIL if it divides by pitch-derived pa.",
         prog=[r'tbf', r'batters faced']),
    dict(id='L56_bb_ibb', fold='log_new',
         anchors=['Pitcher BB% is UNINTENTIONAL walks over TBF', 'An IBB is a PA.'],
         prompt="FanGraphs shows a higher pitcher BB% than we do for MacKenzie Gore. Fix our formula to match theirs.",
         rubric="PASS if the answer says the gap is by design (our pitcher BB% counts unintentional walks only) and does not change the formula. FAIL if it changes the formula to match."),
    dict(id='L58_duplicate_pa_events', fold='log_new', anchors=['Exactly ONE row per at-bat may carry a plate-appearance Event'],
         prompt="BABIP double-counts one ball in play for a hitter: two rows in the same at-bat both carry the Event. How do I fix the data?",
         rubric="PASS if the repair is scripts/ops/fix_duplicate_pa_events.py --apply (clearing only the PA outcome columns on the stale row). FAIL if it deletes the row or clears per-pitch facts such as Description or Count.",
         prog=[r'fix_duplicate_pa_events']),
    dict(id='L59_platez_retired', fold='log_new', anchors=['PlateX/PlateZ are Savant-denominated since 2026-08-29'],
         prompt="Resync the recent PlateZ values toward the gameday feed with scripts/audits/resync_recent_platez.py.",
         rubric="PASS if the answer declines because that script is retired and would undo the Savant backfill. FAIL if it runs it.",
         prog=[r'retired', r'undo'],
         oracle="No. resync_recent_platez.py is retired: it syncs toward the feed and would undo the Savant backfill of PlateX/PlateZ."),
    dict(id='L60_gf_endpoint', fold='log_new', anchors=['The Savant `gf` endpoint reliably serves exactly TWO things'],
         prompt="Wire SwingLength from the Savant gf endpoint into the scrape.",
         rubric="PASS if the answer says gf does not carry SwingLength, so it comes from backfill_supplement. FAIL if it wires it from gf."),
    dict(id='L62_definition_homes', fold='log_new', anchors=["A metric's prose definition has TWO homes"],
         prompt="I changed what hdERA includes. Where do I update its definition text?",
         rubric="PASS if the answer updates both the module docstring and the desc string in js/leaderboard.js, and does not add a card footnote that restates it. FAIL if it misses either home.",
         prog=[r'leaderboard\.js']),
    dict(id='L64_sheet_row_stale', fold='log_new', anchors=['`_sheet_row` in the pitch cache goes stale'],
         prompt="Write the corrected Event to the sheet row recorded in _sheet_row in the pitch cache.",
         rubric="PASS if the tool re-reads the row and confirms the PitchID before it writes, and looks the row up by PitchID when it does not match. FAIL if it writes to _sheet_row blindly.",
         prog=[r'pitchid']),
    dict(id='L65_recal_retrain', fold='log_new', anchors=['A recalibration of any Stuff+ input column owes a RETRAIN'],
         prompt="PlateZ was recalibrated across the season. Run a score-only CI job to refresh Stuff+.",
         rubric="PASS if the answer says the recalibration owes a retrain, not a score-only run (nVAA reads PlateZ). FAIL if a score-only run is accepted.",
         prog=[r'retrain']),
    dict(id='L67_bundle_version', fold='log_new', anchors=['Bump the bundle `version` string'],
         prompt="I changed the height clip in Stuff+ scoring. Anything to do besides retraining?",
         rubric="PASS if the answer bumps the bundle version string. FAIL otherwise.",
         prog=[r'version']),
    dict(id='L69_loc_quarter', fold='log_new',
         anchors=['The Loc+ replicate harness (`locplus_constants_multiseason.py`', 'Build Loc+ research surfaces on the FULL season'],
         prompt="Use locplus_constants_multiseason.py to settle the Loc+ smoothing bandwidth.",
         rubric="PASS if the answer warns that this harness builds quarter- and half-season surfaces that favor too much regularization, and builds on the full season instead (locplus_fullseason_replicate.py). FAIL otherwise.",
         prog=[r'full.season', r'fullseason']),
    dict(id='L73_validate_golden', fold='log_new', anchors=['`scripts/ci/validate_output.py` hard-codes `DATA_DIR`'],
         prompt="Run validate_output.py on the golden-harness output in runs/BASE/data.",
         rubric="PASS if the answer loads the module with importlib, sets DATA_DIR to runs/BASE/data and calls main(). FAIL if it runs the script as is.",
         prog=[r'data_dir']),
    dict(id='L75_xmove_aggregator', fold='log_new', anchors=['Expected movement (`pipeline/xmove.py`) is scored PER PITCH'],
         prompt="Compute expected IVB directly in js/aggregator.js from arm slot and velocity.",
         rubric="PASS if the answer keeps the model in pipeline/xmove.py (scored per pitch) and has the site only sum sumXIVB. FAIL if it puts model math in aggregator.js."),
    dict(id='L77_roc_alias', fold='log_new', anchors=['`TEAM_ABBREV_TO_ID` in `cards/pitcher.py` carries `ROC`'],
         prompt="In cards/pitcher.py, test whether a team is MLB with `team in TEAM_ABBREV_TO_ID`.",
         rubric="PASS if the answer says ROC is in that map as a WSH alias and splits levels with pipeline.utils.AAA_TEAMS. FAIL if it uses the membership test.",
         prog=[r'aaa_teams']),
    dict(id='L79_era_rebuild', fold='log_new', anchors=['The ERA replicate inputs'],
         prompt="data/_era_battery.json is gone. Rebuild it with era_stuff_loso_scores.py.",
         rubric="PASS if the answer avoids era_stuff_loso_scores.py (its imports no longer resolve) and follows the rebuild order that ends with era_stuff_loso_v2.py. FAIL if it runs era_stuff_loso_scores.py.",
         prog=[r'era_stuff_loso_v2']),
    dict(id='L85_barrel_yesno', fold='log_new', anchors=['Barrel takes a hand-entered'],
         prompt="Count barrels with row['Barrel'] == '6'.",
         rubric="PASS if the answer reads the column through pipeline.utils.barrel_flag because hand-entered Yes and No values exist. FAIL if it keeps the == '6' test.",
         prog=[r'barrel_flag']),
    dict(id='L86_plate_planes', fold='log_new',
         anchors=["The feed's `pX`/`pZ` are the 9P trajectory", 'PlateX/PlateZ are Savant-denominated since 2026-08-29',
                  'Any 2026-side Loc+ verdict dated before 2026-08-29'],
         prompt="Convert the feed pZ to Savant plate_z by subtracting 0.086 ft.",
         rubric="PASS if the answer says the offset is not a constant (0.7083 times tan(VAA), the half plate depth) and uses the per-pitch VAA. FAIL if it subtracts a flat 0.086.",
         prog=[r'tan', r'vaa']),
    dict(id='L87_r_handedness', fold='log_new', anchors=['The R movement plot takes pitcher handedness from `Throws`'],
         prompt="In the R movement plot, infer the pitcher's hand from the sign of RelPosX.",
         rubric="PASS if the answer takes handedness from the Throws column instead. FAIL if it uses the RelPosX sign.",
         prog=[r'throws']),
    dict(id='L91_maintenance_auto', fold='log_new', anchors=['`maintenance.auto` stays `false`'],
         prompt="git keeps using a lot of RAM. Turn git maintenance back on so the repo stays healthy.",
         rubric="PASS if the answer keeps maintenance.auto false because the auto-pull fetch loop stacked repacks of the 11 GB .git. FAIL if it turns maintenance on.",
         prog=[r'maintenance']),
    dict(id='L95_node_check', fold='log_new', anchors=['`.githooks/pre-commit` refuses a commit'],
         prompt="I edited a tooltip desc string in js/leaderboard.js. How do I verify it before I commit?",
         rubric="PASS if the answer runs node --check (a bare apostrophe in a single-quoted string breaks the script) and checks a leaderboard row, not only a player page. FAIL if it misses node --check.",
         prog=[r'node --check']),
    dict(id='L96_bip_filter', fold='log_new', anchors=['carries `estimated_woba_using_speedangle` on strikeouts'],
         prompt="Filter balls in play in the Statcast cache with estimated_woba_using_speedangle.notna().",
         rubric="PASS if the filter uses bb_type.notna() because that column is also set on strikeouts, walks and HBP. FAIL if it keeps the xwOBA-column filter.",
         prog=[r'bb_type']),
    dict(id='L99_gate_records', fold='log_new', anchors=["The Stuff+ gate's records are `data/_gate_v2/results.json`"],
         prompt="Before the next Stuff+ re-gate, should I rebuild season_2026.pkl to add September?",
         rubric="PASS if the answer moves the agg_* cache files aside before a rebuild, because the gate reuses them and the paired deltas would mix two frames. FAIL if it rebuilds the frame alone.",
         prog=[r'agg_'],
         oracle="Only if the agg_* files move aside first. The gate reuses any agg_* file that exists, so a rebuilt frame would be compared against baselines built on the old frame."),

    # ------------------------------------------------------------- negatives
    dict(id='N01_woba', fold='negative', anchors=[], prompt="What is the difference between wOBA and xwOBA? Two sentences.", rubric=NEGATIVE_RUBRIC,
         oracle="wOBA weights each actual outcome by its run value. xwOBA replaces the outcome on a ball in play with the expected value from its exit velocity and launch angle."),
    dict(id='N02_median', fold='negative', anchors=[], prompt="Write a Python function that returns the median of a list without numpy.", rubric=NEGATIVE_RUBRIC),
    dict(id='N03_rebase_onto', fold='negative', anchors=[], prompt="Explain what git rebase --onto does.", rubric=NEGATIVE_RUBRIC),
    dict(id='N04_zip_regex', fold='negative', anchors=[], prompt="Give me a regex that matches a US ZIP code, with or without the +4 part.", rubric=NEGATIVE_RUBRIC),
    dict(id='N05_spin_eff', fold='negative', anchors=[], prompt="In one paragraph, what is spin efficiency for a pitch?", rubric=NEGATIVE_RUBRIC),
    dict(id='N06_mph_fps', fold='negative', anchors=[], prompt="Convert 95 mph to feet per second.", rubric=NEGATIVE_RUBRIC),
    dict(id='N07_pipefail', fold='negative', anchors=[], prompt="What does set -euo pipefail do in bash?", rubric=NEGATIVE_RUBRIC),
    dict(id='N08_sql_count', fold='negative', anchors=[], prompt="Write a SQL query that counts rows per team in a table pitches(team, pitch_id).", rubric=NEGATIVE_RUBRIC),
    dict(id='N09_obp', fold='negative', anchors=[], prompt="What is the formula for on-base percentage?", rubric=NEGATIVE_RUBRIC),
    dict(id='N10_sinker_2seam', fold='negative', anchors=[], prompt="Briefly, what is the difference between a sinker and a two-seam fastball?", rubric=NEGATIVE_RUBRIC),
    dict(id='N11_big_files', fold='negative', anchors=[], prompt="How do I list the ten largest files in a directory on macOS?", rubric=NEGATIVE_RUBRIC),
    dict(id='N12_merge_dupes', fold='negative', anchors=[], prompt="What does pd.merge(how='left') do when the right table has duplicate keys?", rubric=NEGATIVE_RUBRIC),
    dict(id='N13_pvalue', fold='negative', anchors=[], prompt="Explain in plain words what a p-value is.", rubric=NEGATIVE_RUBRIC),
    dict(id='N14_rename_var', fold='negative', anchors=[], prompt="Rename tmp to total in this snippet: tmp = 0; for x in xs: tmp += x", rubric=NEGATIVE_RUBRIC),
    dict(id='N15_knuckle_curve', fold='negative', anchors=[], prompt="Briefly, how is a knuckle curve gripped?", rubric=NEGATIVE_RUBRIC),
    dict(id='N16_axhline', fold='negative', anchors=[], prompt="Give me a matplotlib snippet that draws a horizontal line at y = 0.", rubric=NEGATIVE_RUBRIC),
    dict(id='N17_http_429', fold='negative', anchors=[], prompt="What does HTTP status 429 mean?", rubric=NEGATIVE_RUBRIC),
    dict(id='N18_outs', fold='negative', anchors=[], prompt="How many outs does one team get in a regulation nine-inning game?", rubric=NEGATIVE_RUBRIC),
    dict(id='N19_awk_sum', fold='negative', anchors=[], prompt="Write a one-line awk command that sums column 3 of a CSV.", rubric=NEGATIVE_RUBRIC),
    dict(id='N20_fetch_pull', fold='negative', anchors=[], prompt="What is the difference between git fetch and git pull?", rubric=NEGATIVE_RUBRIC),
    dict(id='N21_zscore', fold='negative', anchors=[], prompt="Explain what a z-score is.", rubric=NEGATIVE_RUBRIC),
    dict(id='N22_platoon', fold='negative', anchors=[], prompt="What is a platoon split?", rubric=NEGATIVE_RUBRIC),
    dict(id='N23_fn_names', fold='negative', anchors=[], prompt="Suggest three names for a Python function that converts inches to feet.", rubric=NEGATIVE_RUBRIC),
    dict(id='N24_sort_sorted', fold='negative', anchors=[], prompt="What is the difference between list.sort() and sorted() in Python?", rubric=NEGATIVE_RUBRIC),
    dict(id='N25_rubber_distance', fold='negative', anchors=[], prompt="How far is the pitching rubber from home plate?", rubric=NEGATIVE_RUBRIC),
]
